export * from './components';
export * from './editor';
export * from './editor/fields';
export * from './charts';
export * from './designer';
export * from './ScreenEditor';
export * from './ApiConfigContext';

import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faAlignCenter,
  faAlignLeft,
  faAlignRight,
  faAngleDown,
  faAngleUp,
  faCamera,
  faExpand,
  faSquareFull,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleNotch,
  faEllipsisH,
  faEllipsisV,
  faImages,
  faThLarge,
  faMinus,
  faPlus,
  faHorizontalRule,
  faSpinner,
  faTrash,
  faSearch,
  faSave,
  faEye,
  faEyeSlash,
  faText,
  faMapMarked,
  faBullseyePointer,
  faDraftingCompass,
  faUndo,
  faRedo,
  faChartBar,
  faChartPie,
  faStars,
  faTable,
  faTimes,
  faFile,
  faFolder,
} from '@fortawesome/pro-light-svg-icons';

library.add(
  faEllipsisV,
  faEllipsisH,
  faCamera,
  faExpand,
  faFolder,
  faSquareFull,
  faHorizontalRule,
  faPlus,
  faTrash,
  faSpinner,
  faMinus,
  faImages,
  faThLarge,
  faAngleDown,
  faAngleUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleNotch,
  faAlignCenter,
  faAlignLeft,
  faAlignRight,
  faSearch,
  faSave,
  faEye,
  faEyeSlash,
  faText,
  faMapMarked,
  faBullseyePointer,
  faDraftingCompass,
  faUndo,
  faRedo,
  faChartBar,
  faChartPie,
  faStars,
  faTable,
  faFile,
  faTimes
);
